<?php
session_start();
if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header("Location: ../login.php");
    exit;
}

$pageTitle = "Add New Project";
require_once '../includes/layout_header.php';
?>

<div class="page-header">
    <div class="page-header-left">
        <h1>Add New Project</h1>
        <p>Create a new portfolio entry.</p>
    </div>
</div>

<div class="card">
    <?php if(isset($_GET['success'])): ?>
        <div class="alert alert-success"><i class="fa-solid fa-check-circle"></i> Project added successfully!</div>
    <?php endif; ?>
    
    <?php if(isset($_GET['error'])): ?>
        <div class="alert alert-error"><i class="fa-solid fa-exclamation-circle"></i> Error: <?php echo htmlspecialchars($_GET['error']); ?></div>
    <?php endif; ?>

    <form action="../api/add_project.php" method="POST" enctype="multipart/form-data" id="addProjectForm">
        
        <!-- Basic Info -->
        <div class="form-section-title"><i class="fa-solid fa-info-circle"></i> Basic Information</div>

        <!-- Slug is hidden and auto-generated by JS -->
        <div class="form-group" style="display: none;">
            <label for="slug">URL Slug</label>
            <input type="text" id="slug" name="slug" required placeholder="e.g. euphoria-2024 (auto-generated from title)">
            <span class="form-help">Unique URL identifier. Use lowercase letters, numbers, and hyphens only.</span>
        </div>

        <div class="form-group">
            <label for="title">Project Title</label>
            <input type="text" id="title" name="title" required placeholder="e.g. Euphoria 2024">
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="year">Academic Year</label>
                <input type="text" id="year" name="year" required placeholder="e.g. 2024">
            </div>
            <div class="form-group">
                <label for="batch">Batch</label>
                <input type="text" id="batch" name="batch" placeholder="e.g. 2022-2024">
            </div>
        </div>

        <div class="form-group">
            <label for="short_description">Short Description</label>
            <input type="text" id="short_description" name="short_description" placeholder="Brief description (max 300 chars)" maxlength="300">
            <span class="form-help">Shown on project cards. Keep it concise.</span>
        </div>

        <div class="form-group">
            <label for="description">Full Description</label>
            <textarea id="description" name="description" required placeholder="Detailed project description..."></textarea>
        </div>

        <div class="form-group">
            <label for="objectives">Objectives</label>
            <textarea id="objectives" name="objectives" placeholder="Project objectives..."></textarea>
        </div>

        <div class="form-group">
            <label for="problem_statement">Problem Statement</label>
            <textarea id="problem_statement" name="problem_statement" placeholder="What problem does this project solve?"></textarea>
        </div>

        <div class="form-group">
            <label for="expected_outcome">Expected Outcome</label>
            <textarea id="expected_outcome" name="expected_outcome" placeholder="Expected results and impact..."></textarea>
        </div>

        <!-- Classification -->
        <div class="form-section-title"><i class="fa-solid fa-tags"></i> Classification</div>

        <div class="form-row">
            <div class="form-group">
                <label for="department">Department</label>
                <select id="department" name="department">
                    <option value="MCA">MCA</option>
                    <option value="BCA">BCA</option>
                    <option value="Computer Science">Computer Science</option>
                    <option value="Other">Other</option>
                </select>
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                <select id="category" name="category">
                    <option value="Web Application">Web Application</option>
                    <option value="Mobile Application">Mobile Application</option>
                    <option value="Desktop Application">Desktop Application</option>
                    <option value="Platform">Platform</option>
                    <option value="Other">Other</option>
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="project_type">Project Type</label>
                <select id="project_type" name="project_type">
                    <option value="Academic">Academic</option>
                    <option value="Client">Client</option>
                    <option value="Internal">Internal</option>
                </select>
            </div>
            <div class="form-group">
                <label for="status">Status</label>
                <select id="status" name="status">
                    <option value="Completed">Completed</option>
                    <option value="Deployed">Deployed</option>
                    <option value="In Development">In Development</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="duration">Duration</label>
            <input type="text" id="duration" name="duration" placeholder="e.g. 6 months">
        </div>

        <!-- Technologies -->
        <div class="form-section-title"><i class="fa-solid fa-microchip"></i> Technologies</div>

        <div class="form-group">
            <label>Tech Stack</label>
            <div class="tech-tags-input-wrapper" id="techTagsWrapper">
                <input type="text" class="tech-tags-text-input" id="techTagsInput" placeholder="Type and press Enter...">
            </div>
            <input type="hidden" name="tech_stack" id="techStackHidden">
            <span class="form-help">Press Enter or comma to add a technology tag.</span>
        </div>

        <!-- Key Features -->
        <div class="form-section-title"><i class="fa-solid fa-list-check"></i> Key Features</div>

        <div class="form-group">
            <label>Features</label>
            <div class="tech-tags-input-wrapper" id="featuresWrapper">
                <input type="text" class="tech-tags-text-input" id="featuresInput" placeholder="Type a feature and press Enter...">
            </div>
            <input type="hidden" name="key_features" id="keyFeaturesHidden">
            <span class="form-help">Add features like "Authentication", "Dashboard", "Reports", etc.</span>
        </div>

        <!-- Faculty -->
        <div class="form-section-title"><i class="fa-solid fa-user-tie"></i> Faculty Information</div>

        <div class="form-group">
            <div class="faculty-members-container" id="faculty-members-container">
                <div class="faculty-member-row" style="display:flex; gap:0.5rem; margin-bottom:0.5rem;">
                    <input type="text" name="faculty_names[]" placeholder="Faculty Name" style="flex: 1;">
                    <input type="text" name="faculty_designations[]" placeholder="Designation" style="flex: 1;">
                    <input type="file" name="faculty_photos[]" accept="image/*" style="flex: 1;">
                    <button type="button" class="btn-remove" onclick="this.parentElement.remove()"><i class="fas fa-times"></i></button>
                </div>
            </div>
            <button type="button" class="btn-add" onclick="addFacultyRow()" style="margin-top:0.5rem;"><i class="fas fa-plus"></i> Add Faculty</button>
        </div>

        <!-- Team Members -->
        <div class="form-section-title"><i class="fa-solid fa-users"></i> Team Members</div>
        
        <div class="form-group">
            <div class="team-members-container" id="team-members-container">
                <div class="team-member-row" style="display:flex; gap:0.5rem; margin-bottom:0.5rem;">
                    <input type="text" name="member_names[]" placeholder="Student Name" style="flex: 1;">
                    <input type="text" name="member_roles[]" placeholder="Role (optional)" style="flex: 1;">
                    <input type="text" name="member_linkedin[]" placeholder="LinkedIn URL (optional)" style="flex: 1.5;">
                    <input type="file" name="member_photos[]" accept="image/*" style="flex: 1;">
                    <button type="button" class="btn-remove" onclick="this.parentElement.remove()"><i class="fas fa-times"></i></button>
                </div>
            </div>
            <button type="button" class="btn-add" onclick="addMemberRow()"><i class="fas fa-plus"></i> Add Member</button>
        </div>

        <!-- Images -->
        <div class="form-section-title"><i class="fa-solid fa-images"></i> Images</div>

        <div class="form-group">
            <label for="image">Project Cover Image / Thumbnail</label>
            <input type="file" id="image" name="image" accept="image/*" required>
            <span class="form-help">Max size 5MB. Recommended: WebP or JPG. This will be used as the project thumbnail.</span>
        </div>

        <div class="form-group">
            <label for="screenshots">Additional Screenshots</label>
            <input type="file" id="screenshots" name="screenshots[]" accept="image/*" multiple>
            <span class="form-help">Select multiple images. These will be shown in the project gallery.</span>
        </div>

        <div class="form-group">
            <label for="poster">Project Poster (optional)</label>
            <input type="file" id="poster" name="poster" accept="image/*">
        </div>

        <!-- Links -->
        <div class="form-section-title"><i class="fa-solid fa-link"></i> Links</div>

        <div class="form-row">
            <div class="form-group">
                <label for="github_link">GitHub Link</label>
                <input type="url" id="github_link" name="github_link" placeholder="https://github.com/...">
            </div>
            <div class="form-group">
                <label for="demo_link">Demo Link</label>
                <input type="url" id="demo_link" name="demo_link" placeholder="https://...">
            </div>
        </div>

        <!-- SSL Certificate Module -->
        <div class="form-section-title"><i class="fa-solid fa-shield-halved"></i> SSL Certificate Details (Optional)</div>
        <div class="form-row">
            <div class="form-group">
                <label for="ssl_domain">Domain URL</label>
                <input type="url" id="ssl_domain" name="ssl_domain" placeholder="https://example.com">
            </div>
            <div class="form-group">
                <label for="ssl_provider">Provider</label>
                <input type="text" id="ssl_provider" name="ssl_provider" placeholder="Let's Encrypt">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                <label for="ssl_issue_date">Issue Date</label>
                <input type="date" id="ssl_issue_date" name="ssl_issue_date">
            </div>
            <div class="form-group">
                <label for="ssl_expiry_date">Expiry Date</label>
                <input type="date" id="ssl_expiry_date" name="ssl_expiry_date">
            </div>
        </div>

        <button type="submit" class="btn-submit full-width"><i class="fa-solid fa-rocket"></i> Add Project</button>
    </form>
</div>

<script>
    // ---- Team Member Rows ----
    function addMemberRow() {
        const container = document.getElementById('team-members-container');
        const row = document.createElement('div');
        row.className = 'team-member-row';
        row.innerHTML = `
            <input type="text" name="member_names[]" placeholder="Student Name" style="flex: 1;">
            <input type="text" name="member_roles[]" placeholder="Role (optional)" style="flex: 1;">
            <input type="text" name="member_linkedin[]" placeholder="LinkedIn URL (optional)" style="flex: 1.5;">
            <input type="file" name="member_photos[]" accept="image/*" style="flex: 1;">
            <button type="button" class="btn-remove" onclick="this.parentElement.remove()"><i class="fas fa-times"></i></button>
        `;
        container.appendChild(row);
    }

    // ---- Dynamic Tag Input ----
    function setupTagInput(wrapperId, inputId, hiddenId) {
        const wrapper = document.getElementById(wrapperId);
        const input = document.getElementById(inputId);
        const hidden = document.getElementById(hiddenId);
        if (!wrapper || !input || !hidden) return;

        const tags = [];

        function addTag(value) {
            value = value.trim();
            if (!value || tags.includes(value)) return;
            tags.push(value);
            updateUI();
        }

        function removeTag(value) {
            const idx = tags.indexOf(value);
            if (idx !== -1) tags.splice(idx, 1);
            updateUI();
        }

        function updateUI() {
            // Remove old chips
            wrapper.querySelectorAll('.tech-tag-chip').forEach(el => el.remove());
            // Add chips before input
            tags.forEach(tag => {
                const chip = document.createElement('span');
                chip.className = 'tech-tag-chip';
                chip.innerHTML = `${tag} <button type="button" onclick="event.stopPropagation();">&times;</button>`;
                chip.querySelector('button').addEventListener('click', () => removeTag(tag));
                wrapper.insertBefore(chip, input);
            });
            hidden.value = tags.join(',');
        }

        input.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' || e.key === ',') {
                e.preventDefault();
                addTag(input.value);
                input.value = '';
            }
            if (e.key === 'Backspace' && !input.value && tags.length > 0) {
                removeTag(tags[tags.length - 1]);
            }
        });

        wrapper.addEventListener('click', () => input.focus());
    }

    setupTagInput('techTagsWrapper', 'techTagsInput', 'techStackHidden');
    setupTagInput('featuresWrapper', 'featuresInput', 'keyFeaturesHidden');

    // ---- Auto-generate slug from title ----
    const titleInput = document.getElementById('title');
    const slugInput = document.getElementById('slug');
    if (titleInput && slugInput) {
        titleInput.addEventListener('input', () => {
            if (!slugInput.dataset.manual) {
                slugInput.value = titleInput.value
                    .toLowerCase()
                    .replace(/[^a-z0-9\s-]/g, '')
                    .replace(/\s+/g, '-')
                    .replace(/-+/g, '-')
                    .trim();
            }
        });
        slugInput.addEventListener('input', () => {
            slugInput.dataset.manual = '1';
        });
    }
    // ---- Faculty Member Rows ----
    function addFacultyRow() {
        const container = document.getElementById('faculty-members-container');
        const row = document.createElement('div');
        row.className = 'faculty-member-row';
        row.style.display = 'flex';
        row.style.gap = '0.5rem';
        row.style.marginBottom = '0.5rem';
        row.innerHTML = `
            <input type="text" name="faculty_names[]" placeholder="Faculty Name" style="flex: 1;">
            <input type="text" name="faculty_designations[]" placeholder="Designation" style="flex: 1;">
            <input type="file" name="faculty_photos[]" accept="image/*" style="flex: 1;">
            <button type="button" class="btn-remove" onclick="this.parentElement.remove()"><i class="fas fa-times"></i></button>
        `;
        container.appendChild(row);
    }
</script>

<?php require_once '../includes/layout_footer.php'; ?>
